spring:
  datasource:
    name: test
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;TIME ZONE=UTC-5
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
server:
  port: 7634
jwt:
  secret: A31E8C6D5BF7E9A08C6D7E528A4F01B5E26C9D0F387E4A1B5C76D4E7A9081B5A3E28C76D7A08C6D5B7E9A0B4C76D8A4F012E5C6D9A
