spring:
  datasource:
    name: test
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: admin
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true